In [1]:
%load_ext autoreload
%autoreload 2

# Overview of New Tasks Defined with *RTGL*

In [2]:
from rtgl.base import Database
import redelex
from relbench.datasets import get_dataset

/home/kolesiko/CTU/BT/BT/rtgl-tasks/.venv/lib/python3.12/site-packages/torch_geometric/__init__.py:4: UserWarning: An issue occurred while importing 'torch-scatter'. Disabling its usage. Stacktrace: /home/kolesiko/CTU/BT/BT/rtgl-tasks/.venv/lib/python3.12/site-packages/torch_scatter/_version_cuda.so: undefined symbol: _ZN3c106detail14torchCheckFailEPKcS2_jRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
  import torch_geometric.typing
/home/kolesiko/CTU/BT/BT/rtgl-tasks/.venv/lib/python3.12/site-packages/torch_geometric/__init__.py:4: UserWarning: An issue occurred while importing 'torch-cluster'. Disabling its usage. Stacktrace: /home/kolesiko/CTU/BT/BT/rtgl-tasks/.venv/lib/python3.12/site-packages/torch_cluster/_version_cuda.so: undefined symbol: _ZN3c106detail14torchCheckFailEPKcS2_jRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
  import torch_geometric.typing
/home/kolesiko/CTU/BT/BT/rtgl-tasks/.venv/lib/python3.12/site-packages/torch_geometric/__init__.py:4: UserWarning: An issue occurred while importing 'torch-spline-conv'. Disabling its usage. Stacktrace: /home/kolesiko/CTU/BT/BT/rtgl-tasks/.venv/lib/python3.12/site-packages/torch_spline_conv/_version_cuda.so: undefined symbol: _ZN3c106detail14torchCheckFailEPKcS2_jRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
  import torch_geometric.typing
/home/kolesiko/CTU/BT/BT/rtgl-tasks/.venv/lib/python3.12/site-packages/torch_geometric/__init__.py:4: UserWarning: An issue occurred while importing 'torch-sparse'. Disabling its usage. Stacktrace: /home/kolesiko/CTU/BT/BT/rtgl-tasks/.venv/lib/python3.12/site-packages/torch_sparse/_version_cuda.so: undefined symbol: _ZN3c106detail14torchCheckFailEPKcS2_jRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
  import torch_geometric.typing

## CTU-SFScores

In [3]:
dataset = get_dataset("ctu-sfscores", download=False)
db = dataset.get_db(upto_test_timestamp=False)
db = Database(table_dict=db.table_dict)

print(f"Min timestamp: {db.min_timestamp}")
print(f"Max timestamp: {db.max_timestamp}")

Loading Database object from /home/kolesiko/.cache/relbench/ctu-sfscores/db...
Done in 0.04 seconds.
Min timestamp: 2013-10-07 00:00:00
Max timestamp: 2016-12-15 00:00:00

In [4]:
db.table_dict["businesses"]

Table(df=
      __PK__                                name  \
0          0                    Tiramisu Kitchen
1          1  OMNI S.F. Hotel - 2nd Floor Pantry
2          2      Norman's Ice Cream and Freezes
3          3                 CHARLIE'S DELI CAFE
4          4                          ART'S CAFE
...      ...                                 ...
6353    6353             Breaking Bad Sandwiches
6354    6354                       Miller's Rest
6355    6355                            Panuchos
6356    6356            Nobhill Pizza & Shawerma
6357    6357                   Burger King #4668

                            address           city postal_code  latitude  \
0                     033 Belden Pl  San Francisco       94104   37.7911
1     500 California St, 2nd  Floor  San Francisco       94104   37.7929
2               2801 Leavenworth St  San Francisco       94133   37.8072
3                    3202 FOLSOM St           S.F.       94110   37.7471
4                     747 IRVING St  SAN FRANCISCO       94122    37.764
...                             ...            ...         ...       ...
6353              154 McAllister St           <NA>       94102      <NA>
6354                 1085 Sutter St           <NA>       94109      <NA>
6355                620 Broadway St           <NA>       94133      <NA>
6356             1534 California St           <NA>       94109      <NA>
6357               1690 Valencia St  San Francisco       94110      <NA>

      longitude  phone_number tax_code  business_certificate application_date  \
0      -122.404          <NA>      H24                779059              NaT
1      -122.403          <NA>      H24                352312              NaT
2      -122.419          <NA>      H24                346882              NaT
3      -122.414          <NA>      H24                340024       2001-10-10
4      -122.466          <NA>      H24                318022              NaT
...         ...           ...      ...                   ...              ...
6353       <NA>          <NA>      H25               1057025       2016-09-23
6354       <NA>          <NA>      H26               1057746       2016-09-23
6355       <NA>          <NA>      H24               1042408       2016-09-28
6356       <NA>          <NA>      H24               1051081       2016-09-29
6357       <NA>          <NA>      H29                459309       2016-10-03

                             owner_name                 owner_address  \
0                          Tiramisu LLC                  33 Belden St
1         OMNI San Francisco Hotel Corp  500 California St, 2nd Floor
2                      Norman Antiforda           2801 Leavenworth St
3             HARB, CHARLES AND KRISTIN                  1150 SANCHEZ
4                        YOON HAE RYONG              1567 FUNSTON AVE
...                                 ...                           ...
6353                          JPMD, LLC            662 Bellhurst Lane
6354                 Miller's Rest, LLC              2906 Bush Street
6355                    Los Aluxes, LLC      1032 Irving Street, #421
6356                    BBA Foods, Inc.         840 Post Street, #218
6357  Golden Gate Restaurant Group, Inc                    P.O Box 21

         owner_city owner_state owner_zip
0     San Francisco          CA     94104
1     San Francisco          CA     94104
2     San Francisco          CA     94133
3              S.F.          CA     94114
4     SAN FRANCISCO          CA     94122
...             ...         ...       ...
6353  Castro Valley          CA     94102
6354  San Francisco          CA     94109
6355  San Francisco          CA     94122
6356  San Francisco          CA     94109
6357      Lafeyette          CA     94549

[6358 rows x 16 columns],
  fkey_col_to_pkey_table={},
  pkey_col=__PK__,
  time_col=None)

In [5]:
db.table_dict["inspections"]

Table(df=
       __PK__  business_id  score       date                   type  \
0           0        35786     98 2013-10-07  Routine - Unscheduled
1           1         3859     86 2013-10-07  Routine - Unscheduled
2           2        16513     88 2013-10-07  Routine - Unscheduled
3           3        61427   <NA> 2013-10-07  Reinspection/Followup
4           4        73978     85 2013-10-07  Routine - Unscheduled
...       ...          ...    ...        ...                    ...
23759   23759        85972     75 2016-10-05  Routine - Unscheduled
23760   23760        36850     88 2016-10-05  Routine - Unscheduled
23761   23761        71131     81 2016-10-05  Routine - Unscheduled
23762   23762        80587     83 2016-10-05  Routine - Unscheduled
23763   23763        85899   <NA> 2016-12-15          New Ownership

       FK_businesses_business_id
0                           2291
1                            937
2                           1872
3                           2743
4                           4044
...                          ...
23759                       5967
23760                       2360
23761                       3875
23762                       5042
23763                       5944

[23764 rows x 6 columns],
  fkey_col_to_pkey_table={'FK_businesses_business_id': 'businesses'},
  pkey_col=__PK__,
  time_col=date)

In [6]:
tbl = db.table_dict["inspections"].df
tbl[tbl["FK_businesses_business_id"] == 937]

,__PK__,business_id,score,date,type,FK_businesses_business_id
1,1,3859,86,2013-10-07,Routine - Unscheduled,937
624,624,3859,<NA>,2013-11-01,Reinspection/Followup,937
1387,1387,3859,<NA>,2013-12-10,New Construction,937
5657,5657,3859,96,2014-05-22,Routine - Unscheduled,937
22516,22516,3859,87,2016-08-17,Routine - Unscheduled,937
23229,23229,3859,<NA>,2016-09-14,Reinspection/Followup,937

### Businesses Scores Temporal Task

In [7]:
from rtgl_tasks.tasks import SFScoresBusinessesScoresTmpTask

task = SFScoresBusinessesScoresTmpTask()

In [8]:
task.get_table("train")

Loading Database object from /home/kolesiko/.cache/relbench/ctu-sfscores/db...
Done in 0.01 seconds.

------------------ Table ------------------
DataFrame:
        fk  timestamp  label
0        0 2013-12-19     92
1        1 2013-12-19     96
2        4 2013-12-19     92
3        5 2013-12-19     92
4        6 2013-12-19    100
...    ...        ...    ...
7780  5913 2015-06-18     86
7781  5914 2015-06-18    100
7782  5929 2015-06-18     94
7783  5933 2015-06-18     74
7784  5949 2015-06-18     74

[7785 rows x 3 columns]
Foreign Key Columns to Primary Key Tables: {'fk': 'businesses'}
Primary Key Column: None
Time Column: timestamp
-------------------------------------------

In [9]:
task.get_table("val")

------------------ Table ------------------
DataFrame:
        fk  timestamp  label
0        0 2015-12-17     82
1        1 2015-12-17     96
2        3 2015-12-17     84
3        6 2015-12-17     88
4        7 2015-12-17     73
...    ...        ...    ...
2243  6188 2015-12-17     96
2244  6198 2015-12-17     96
2245  6234 2015-12-17    100
2246  6249 2015-12-17     91
2247  6256 2015-12-17     98

[2248 rows x 3 columns]
Foreign Key Columns to Primary Key Tables: {'fk': 'businesses'}
Primary Key Column: None
Time Column: timestamp
-------------------------------------------

In [10]:
task.get_table("test")

------------------ Table ------------------
DataFrame:
        fk  timestamp  label
0        2 2016-06-16     84
1        4 2016-06-16     94
2        6 2016-06-16     90
3        8 2016-06-16     94
4        9 2016-06-16    100
...    ...        ...    ...
1639  6340 2016-06-16     90
1640  6343 2016-06-16    100
1641  6344 2016-06-16    100
1642  6345 2016-06-16    100
1643  6347 2016-06-16    100

[1644 rows x 3 columns]
Foreign Key Columns to Primary Key Tables: {'fk': 'businesses'}
Primary Key Column: None
Time Column: timestamp
-------------------------------------------

In [11]:
task.get_table("test", hide_labels=True)

------------------ Table ------------------
DataFrame:
        fk  timestamp
0        2 2016-06-16
1        4 2016-06-16
2        6 2016-06-16
3        8 2016-06-16
4        9 2016-06-16
...    ...        ...
1639  6340 2016-06-16
1640  6343 2016-06-16
1641  6344 2016-06-16
1642  6345 2016-06-16
1643  6347 2016-06-16

[1644 rows x 2 columns]
Foreign Key Columns to Primary Key Tables: {'fk': 'businesses'}
Primary Key Column: None
Time Column: timestamp
-------------------------------------------

## CTU-Stats

In [12]:
dataset = get_dataset("ctu-stats", download=False)
db = dataset.get_db(upto_test_timestamp=False)
db = Database(table_dict=db.table_dict)

print(f"Min timestamp: {db.min_timestamp}")
print(f"Max timestamp: {db.max_timestamp}")

Loading Database object from /home/kolesiko/.cache/relbench/ctu-stats/db...
Done in 0.92 seconds.
Min timestamp: 2009-02-02 00:00:00
Max timestamp: 2014-09-14 02:54:13

In [13]:
tbl = db.table_dict["comments"]

In [14]:
db.table_dict["postLinks"]

Table(df=
       __PK__        CreationDate  PostId  RelatedPostId  LinkTypeId  \
0           0 2010-07-21 14:47:33     395            173           1
1           1 2010-07-23 16:30:41     548            539           1
2           2 2010-07-26 20:12:15     375             30           1
3           3 2010-07-27 16:00:22     769             31           1
4           4 2010-07-27 16:00:22     769              6           1
...       ...                 ...     ...            ...         ...
11097   11097 2014-09-13 09:51:24  104882         104565           1
11098   11098 2014-09-13 14:24:45  115343          51061           1
11099   11099 2014-09-13 15:07:09  115304           5135           3
11100   11100 2014-09-13 18:43:55  115327          31326           3
11101   11101 2014-09-13 20:54:31  115360          60438           1

       FK_posts_PostId  FK_posts_RelatedPostId
0                  395                     185
1                  544                     535
2                  376                      52
3                  748                      53
4                  748                      28
...                ...                     ...
11097            83625                   83348
11098            91943                   42212
11099            91906                    4772
11100            91927                   28080
11101            91957                   48985

[11102 rows x 7 columns],
  fkey_col_to_pkey_table={'FK_posts_PostId': 'posts', 'FK_posts_RelatedPostId': 'posts'},
  pkey_col=__PK__,
  time_col=CreationDate)

In [15]:
tbl = db.table_dict["tags"]
tbl

Table(df=
      __PK__                  TagName  Count  ExcerptPostId  WikiPostId  \
0          0                 bayesian   1342          20258       20257
1          1                    prior    168          62158       62157
2          2              elicitation      6           <NA>        <NA>
3          3                normality    191          67815       67814
4          4              open-source     13           <NA>        <NA>
...      ...                      ...    ...            ...         ...
1027    1027                 roxygen2      1           <NA>        <NA>
1028    1028      package-development      1           <NA>        <NA>
1029    1029  generilzed-linear-model      1           <NA>        <NA>
1030    1030                 standard      1           <NA>        <NA>
1031    1031            zero-inflated      1           <NA>        <NA>

      FK_posts_ExcerptPostId
0                      18467
1                      50394
2                       <NA>
3                      55163
4                       <NA>
...                      ...
1027                    <NA>
1028                    <NA>
1029                    <NA>
1030                    <NA>
1031                    <NA>

[1032 rows x 6 columns],
  fkey_col_to_pkey_table={'FK_posts_ExcerptPostId': 'posts'},
  pkey_col=__PK__,
  time_col=None)

In [16]:
tbl.df[tbl.df["ExcerptPostId"] == 67815]

   __PK__    TagName  Count  ExcerptPostId  WikiPostId  FK_posts_ExcerptPostId
3       3  normality    191          67815       67814                   55163

### User Reputation Static Task

In [17]:
from rtgl_tasks.tasks import StatsUserReputationStatTask

In [18]:
task = StatsUserReputationStatTask()

In [19]:
task.get_table("train")

------------------ Table ------------------
DataFrame:
          fk  label
11542  24113      1
9561   19562      1
10441  21529      1
2157    3900    101
14400  31847     31
...      ...    ...
6144   11987     21
14375  31778      1
16126  37144      1
6344   12426    116
14778  32973      1

[13628 rows x 2 columns]
Foreign Key Columns to Primary Key Tables: {'fk': 'users'}
Primary Key Column: None
Time Column: None
-------------------------------------------

In [20]:
task.get_table("val")

------------------ Table ------------------
DataFrame:
          fk  label
12643  26714      1
2293    4160   1200
3993    7675      1
5439   10533      8
130      188    184
...      ...    ...
6638   12995    140
1913    3434     21
7657   15298    108
9400   19220     31
7827   15692     11

[1704 rows x 2 columns]
Foreign Key Columns to Primary Key Tables: {'fk': 'users'}
Primary Key Column: None
Time Column: None
-------------------------------------------

In [21]:
task.get_table("test")

------------------ Table ------------------
DataFrame:
          fk  label
1          2    101
16        23   3150
38        51    549
55        73  14082
72        94    708
...      ...    ...
16980  40084      6
16988  40124    138
16999  40168      1
17021  40251    114
17032  40314      1

[1703 rows x 2 columns]
Foreign Key Columns to Primary Key Tables: {'fk': 'users'}
Primary Key Column: None
Time Column: None
-------------------------------------------

In [22]:
task.get_table("test", hide_labels=True)

------------------ Table ------------------
DataFrame:
          fk
1          2
16        23
38        51
55        73
72        94
...      ...
16980  40084
16988  40124
16999  40168
17021  40251
17032  40314

[1703 rows x 1 columns]
Foreign Key Columns to Primary Key Tables: {'fk': 'users'}
Primary Key Column: None
Time Column: None
-------------------------------------------

### Post Tags Static Task

In [23]:
from rtgl_tasks.tasks import StatsPostTagsStatTask

In [24]:
task = StatsPostTagsStatTask()

In [25]:
task.get_table("train")

------------------ Table ------------------
DataFrame:
        fk  label
188  34218  [481]
238  40656  [772]
462  56273  [868]
465  56346    [9]
182  33730  [126]
..     ...    ...
397  53887   [10]
254  43397  [791]
217  37518  [518]
4     2815   [32]
256  43666  [736]

[477 rows x 2 columns]
Foreign Key Columns to Primary Key Tables: {'fk': 'posts', 'label': 'tags'}
Primary Key Column: None
Time Column: None
-------------------------------------------

In [26]:
task.get_table("val")

------------------ Table ------------------
DataFrame:
        fk   label
590  88196  [1003]
476  59116   [602]
308  51074   [818]
121  25836   [339]
567  75159   [375]
252  42662   [171]
448  56090   [480]
543  66164   [694]
413  54969    [81]
510  65092    [78]
454  56114   [580]
13    7740   [369]
292  50578    [40]
138  28645   [139]
466  56358   [226]
458  56159   [841]
391  53469   [218]
230  39594   [766]
105  25392   [199]
251  42643   [744]
313  51301   [826]
270  48863   [513]
47   16974   [147]
58   18680    [31]
213  36982   [750]
372  53036   [711]
102  25386   [145]
226  39184   [434]
455  56123   [770]
162  31895   [724]
100  25381   [326]
459  56162   [205]
288  50455   [342]
498  64200   [494]
64   18729   [159]
554  70086    [16]
504  64452    [64]
427  55761   [594]
406  54055   [637]
529  65292   [541]
389  53395   [228]
520  65265   [209]
52   18103   [352]
475  58547   [658]
593  89400   [122]
99   25378   [204]
269  48859   [809]
160  31526    [84]
339  52250   [183]
214  37081   [755]
27    9918   [400]
430  55784   [740]
161  31672   [383]
106  25395   [376]
241  41604   [119]
315  51329   [299]
343  52536   [645]
14    7916    [27]
1     2297   [143]
387  53294   [193]
Foreign Key Columns to Primary Key Tables: {'fk': 'posts', 'label': 'tags'}
Primary Key Column: None
Time Column: None
-------------------------------------------

In [27]:
task.get_table("test")

------------------ Table ------------------
DataFrame:
        fk  label
20    8367    [6]
21    8492  [301]
32   12955  [250]
34   13102  [524]
40   14915  [124]
61   18685    [7]
62   18688   [38]
71   19876  [261]
80   22870  [466]
87   25312   [29]
91   25333   [20]
98   25374  [317]
128  25998   [47]
130  26737  [693]
134  27306  [702]
156  30747  [516]
166  32578  [718]
171  33264  [393]
187  34216  [348]
189  34286  [362]
191  34291   [17]
200  34610   [18]
201  34613  [222]
205  34949  [647]
215  37093  [756]
216  37409  [447]
243  41608  [490]
260  45122  [798]
267  47623  [328]
273  49740  [162]
276  49905  [814]
295  50613  [397]
327  51460  [435]
330  51487  [136]
337  52240  [239]
345  52654  [838]
359  52886  [263]
366  52943  [451]
378  53051  [341]
379  53053  [461]
385  53255  [192]
401  53940  [648]
417  55063  [819]
418  55157  [850]
435  55820  [776]
461  56194  [430]
471  57944  [874]
474  58503  [878]
484  60740  [883]
489  61789  [127]
491  62486  [775]
492  63888  [608]
508  65020  [259]
541  65845  [543]
559  73074   [48]
560  73183  [297]
562  74193  [668]
579  80456  [970]
581  82044  [808]
Foreign Key Columns to Primary Key Tables: {'fk': 'posts', 'label': 'tags'}
Primary Key Column: None
Time Column: None
-------------------------------------------

In [28]:
task.get_table("test", hide_labels=True)

------------------ Table ------------------
DataFrame:
        fk
20    8367
21    8492
32   12955
34   13102
40   14915
61   18685
62   18688
71   19876
80   22870
87   25312
91   25333
98   25374
128  25998
130  26737
134  27306
156  30747
166  32578
171  33264
187  34216
189  34286
191  34291
200  34610
201  34613
205  34949
215  37093
216  37409
243  41608
260  45122
267  47623
273  49740
276  49905
295  50613
327  51460
330  51487
337  52240
345  52654
359  52886
366  52943
378  53051
379  53053
385  53255
401  53940
417  55063
418  55157
435  55820
461  56194
471  57944
474  58503
484  60740
489  61789
491  62486
492  63888
508  65020
541  65845
559  73074
560  73183
562  74193
579  80456
581  82044
Foreign Key Columns to Primary Key Tables: {'fk': 'posts', 'label': 'tags'}
Primary Key Column: None
Time Column: None
-------------------------------------------

### User Engagement Temporal Task

In [29]:
from rtgl_tasks.tasks import StatsUserEngagementTmpTask

In [30]:
task = StatsUserEngagementTmpTask()

In [31]:
task.get_table("train")

Loading Database object from /home/kolesiko/.cache/relbench/ctu-stats/db...
Done in 0.82 seconds.

------------------ Table ------------------
DataFrame:
          fk  timestamp  label
0          0 2010-09-04   True
1          4 2010-09-04   True
2          5 2010-09-04   True
3          6 2010-09-04   True
4          7 2010-09-04   True
...      ...        ...    ...
62566  24746 2013-11-30  False
62567  24749 2013-11-30   True
62568  24750 2013-11-30  False
62569  24753 2013-11-30   True
62570  24757 2013-11-30  False

[62571 rows x 3 columns]
Foreign Key Columns to Primary Key Tables: {'fk': 'users'}
Primary Key Column: None
Time Column: timestamp
-------------------------------------------

In [32]:
task.get_table("val")

------------------ Table ------------------
DataFrame:
          fk  timestamp  label
0          0 2014-03-01   True
1          2 2014-03-01  False
2          4 2014-03-01  False
3          5 2014-03-01  False
4          6 2014-03-01  False
...      ...        ...    ...
12815  28883 2014-03-01   True
12816  28892 2014-03-01  False
12817  28893 2014-03-01  False
12818  28900 2014-03-01  False
12819  28908 2014-03-01  False

[12820 rows x 3 columns]
Foreign Key Columns to Primary Key Tables: {'fk': 'users'}
Primary Key Column: None
Time Column: timestamp
-------------------------------------------

In [33]:
task.get_table("test")

------------------ Table ------------------
DataFrame:
          fk  timestamp  label
0          0 2014-06-01   True
1          2 2014-06-01  False
2          4 2014-06-01  False
3          5 2014-06-01  False
4          6 2014-06-01  False
...      ...        ...    ...
14754  34124 2014-06-01  False
14755  34134 2014-06-01  False
14756  34137 2014-06-01  False
14757  34141 2014-06-01  False
14758  34144 2014-06-01   True

[14759 rows x 3 columns]
Foreign Key Columns to Primary Key Tables: {'fk': 'users'}
Primary Key Column: None
Time Column: timestamp
-------------------------------------------

In [34]:
task.get_table("test", hide_labels=True)

------------------ Table ------------------
DataFrame:
          fk  timestamp
0          0 2014-06-01
1          2 2014-06-01
2          4 2014-06-01
3          5 2014-06-01
4          6 2014-06-01
...      ...        ...
14754  34124 2014-06-01
14755  34134 2014-06-01
14756  34137 2014-06-01
14757  34141 2014-06-01
14758  34144 2014-06-01

[14759 rows x 2 columns]
Foreign Key Columns to Primary Key Tables: {'fk': 'users'}
Primary Key Column: None
Time Column: timestamp
-------------------------------------------

### User Badge Temporal Task

In [35]:
from rtgl_tasks.tasks import StatsUserBadgeTmpTask

In [36]:
task = StatsUserBadgeTmpTask()

In [37]:
task.get_table("train")

------------------ Table ------------------
DataFrame:
           fk  timestamp  label
0           0 2010-09-04  False
1           1 2010-09-04  False
2           2 2010-09-04  False
3           3 2010-09-04  False
4           4 2010-09-04   True
...       ...        ...    ...
138280  24754 2013-11-30   True
138281  24755 2013-11-30   True
138282  24756 2013-11-30  False
138283  24757 2013-11-30  False
138284  24758 2013-11-30   True

[138285 rows x 3 columns]
Foreign Key Columns to Primary Key Tables: {'fk': 'users'}
Primary Key Column: None
Time Column: timestamp
-------------------------------------------

In [38]:
task.get_table("val")

------------------ Table ------------------
DataFrame:
          fk  timestamp  label
0          0 2014-03-01  False
1          1 2014-03-01  False
2          2 2014-03-01  False
3          3 2014-03-01  False
4          4 2014-03-01   True
...      ...        ...    ...
28910  28910 2014-03-01  False
28911  28911 2014-03-01  False
28912  28912 2014-03-01   True
28913  28913 2014-03-01  False
28914  28914 2014-03-01   True

[28915 rows x 3 columns]
Foreign Key Columns to Primary Key Tables: {'fk': 'users'}
Primary Key Column: None
Time Column: timestamp
-------------------------------------------

In [39]:
task.get_table("test")

------------------ Table ------------------
DataFrame:
          fk  timestamp  label
0          0 2014-06-01  False
1          1 2014-06-01  False
2          2 2014-06-01  False
3          3 2014-06-01  False
4          4 2014-06-01   True
...      ...        ...    ...
34144  34144 2014-06-01  False
34145  34145 2014-06-01   True
34146  34146 2014-06-01   True
34147  34147 2014-06-01  False
34148  34148 2014-06-01  False

[34149 rows x 3 columns]
Foreign Key Columns to Primary Key Tables: {'fk': 'users'}
Primary Key Column: None
Time Column: timestamp
-------------------------------------------

In [40]:
task.get_table("test", hide_labels=True)

------------------ Table ------------------
DataFrame:
          fk  timestamp
0          0 2014-06-01
1          1 2014-06-01
2          2 2014-06-01
3          3 2014-06-01
4          4 2014-06-01
...      ...        ...
34144  34144 2014-06-01
34145  34145 2014-06-01
34146  34146 2014-06-01
34147  34147 2014-06-01
34148  34148 2014-06-01

[34149 rows x 2 columns]
Foreign Key Columns to Primary Key Tables: {'fk': 'users'}
Primary Key Column: None
Time Column: timestamp
-------------------------------------------

### Post Votes Temporal Task

In [41]:
from rtgl_tasks.tasks import StatsPostVotesTmpTask

In [42]:
task = StatsPostVotesTmpTask()

In [43]:
task.get_table("train")

------------------ Table ------------------
DataFrame:
           fk  timestamp  label
0          19 2010-09-04      0
1          23 2010-09-04      3
2          24 2010-09-04      2
3          25 2010-09-04      4
4          26 2010-09-04      2
...       ...        ...    ...
145279  63040 2013-11-30      0
145280  63042 2013-11-30      1
145281  63043 2013-11-30      0
145282  63044 2013-11-30      1
145283  63045 2013-11-30      0

[145284 rows x 3 columns]
Foreign Key Columns to Primary Key Tables: {'fk': 'posts'}
Primary Key Column: None
Time Column: timestamp
-------------------------------------------

In [44]:
task.get_table("val")

------------------ Table ------------------
DataFrame:
          fk  timestamp  label
0         19 2014-03-01      0
1         23 2014-03-01      1
2         24 2014-03-01      0
3         25 2014-03-01      0
4         26 2014-03-01      2
...      ...        ...    ...
30767  71064 2014-03-01      0
30768  71065 2014-03-01      0
30769  71066 2014-03-01      0
30770  71068 2014-03-01      0
30771  71073 2014-03-01      0

[30772 rows x 3 columns]
Foreign Key Columns to Primary Key Tables: {'fk': 'posts'}
Primary Key Column: None
Time Column: timestamp
-------------------------------------------

In [45]:
task.get_table("test")

------------------ Table ------------------
DataFrame:
          fk  timestamp  label
0         19 2014-06-01      0
1         23 2014-06-01      0
2         24 2014-06-01      0
3         25 2014-06-01      0
4         26 2014-06-01      0
...      ...        ...    ...
36125  80885 2014-06-01      0
36126  80892 2014-06-01      0
36127  80893 2014-06-01      0
36128  80896 2014-06-01      3
36129  80897 2014-06-01      1

[36130 rows x 3 columns]
Foreign Key Columns to Primary Key Tables: {'fk': 'posts'}
Primary Key Column: None
Time Column: timestamp
-------------------------------------------

In [46]:
task.get_table("test", hide_labels=True)

------------------ Table ------------------
DataFrame:
          fk  timestamp
0         19 2014-06-01
1         23 2014-06-01
2         24 2014-06-01
3         25 2014-06-01
4         26 2014-06-01
...      ...        ...
36125  80885 2014-06-01
36126  80892 2014-06-01
36127  80893 2014-06-01
36128  80896 2014-06-01
36129  80897 2014-06-01

[36130 rows x 2 columns]
Foreign Key Columns to Primary Key Tables: {'fk': 'posts'}
Primary Key Column: None
Time Column: timestamp
-------------------------------------------

### User Post Comment Temporal Task

In [47]:
from rtgl_tasks.tasks import StatsUserPostCommentTmpTask

In [48]:
task = StatsUserPostCommentTmpTask()

In [49]:
task.get_table("train")

------------------ Table ------------------
DataFrame:
         fk  timestamp                        label
0         5 2010-09-04                       [1187]
1         7 2010-09-04  [1187, 309, 2231, 1461, 98]
2        45 2010-09-04                        [974]
3        58 2010-09-04                  [327, 2162]
4        60 2010-09-04               [174, 338, 98]
...     ...        ...                          ...
2525  24564 2013-11-30               [63021, 55968]
2526  24691 2013-11-30                      [62859]
2527  24735 2013-11-30                      [62953]
2528  24743 2013-11-30                      [62977]
2529  24753 2013-11-30                      [63025]

[2530 rows x 3 columns]
Foreign Key Columns to Primary Key Tables: {'fk': 'users', 'label': 'posts'}
Primary Key Column: None
Time Column: timestamp
-------------------------------------------

In [50]:
task.get_table("val")

------------------ Table ------------------
DataFrame:
        fk  timestamp    label
0       22 2014-03-01  [66030]
1       26 2014-03-01  [15512]
2       42 2014-03-01   [9894]
3       60 2014-03-01   [4788]
4       73 2014-03-01  [45444]
..     ...        ...      ...
355  28764 2014-03-01  [70846]
356  28816 2014-03-01  [71045]
357  28819 2014-03-01  [71059]
358  28864 2014-03-01  [71052]
359  28866 2014-03-01  [71002]

[360 rows x 3 columns]
Foreign Key Columns to Primary Key Tables: {'fk': 'users', 'label': 'posts'}
Primary Key Column: None
Time Column: timestamp
-------------------------------------------

In [51]:
task.get_table("test")

------------------ Table ------------------
DataFrame:
        fk  timestamp           label
0       22 2014-06-01            [69]
1       25 2014-06-01          [2542]
2       26 2014-06-01           [259]
3       60 2014-06-01         [80756]
4      134 2014-06-01  [45364, 75670]
..     ...        ...             ...
367  34035 2014-06-01         [80699]
368  34042 2014-06-01         [80707]
369  34106 2014-06-01         [80825]
370  34119 2014-06-01         [80845]
371  34128 2014-06-01  [80856, 80863]

[372 rows x 3 columns]
Foreign Key Columns to Primary Key Tables: {'fk': 'users', 'label': 'posts'}
Primary Key Column: None
Time Column: timestamp
-------------------------------------------

In [52]:
task.get_table("test", hide_labels=True)

------------------ Table ------------------
DataFrame:
        fk  timestamp
0       22 2014-06-01
1       25 2014-06-01
2       26 2014-06-01
3       60 2014-06-01
4      134 2014-06-01
..     ...        ...
367  34035 2014-06-01
368  34042 2014-06-01
369  34106 2014-06-01
370  34119 2014-06-01
371  34128 2014-06-01

[372 rows x 2 columns]
Foreign Key Columns to Primary Key Tables: {'fk': 'users', 'label': 'posts'}
Primary Key Column: None
Time Column: timestamp
-------------------------------------------

### Post Post Related Temporal Task

In [53]:
from rtgl_tasks.tasks import StatsPostPostRelatedTmpTask

In [54]:
task = StatsPostPostRelatedTmpTask()

In [55]:
task.get_table("train")

------------------ Table ------------------
DataFrame:
        fk  timestamp           label
0       48 2010-09-04           [133]
1      133 2010-09-04           [356]
2      151 2010-09-04            [95]
3      206 2010-09-04           [411]
4      214 2010-09-04            [32]
..     ...        ...             ...
684  62567 2013-11-30         [57844]
685  62792 2013-11-30         [28080]
686  62954 2013-11-30          [2193]
687  62994 2013-11-30         [62923]
688  63028 2013-11-30  [20020, 54665]

[689 rows x 3 columns]
Foreign Key Columns to Primary Key Tables: {'fk': 'posts', 'label': 'posts'}
Primary Key Column: None
Time Column: timestamp
-------------------------------------------

In [56]:
task.get_table("val")

------------------ Table ------------------
DataFrame:
       fk  timestamp         label
0   11291 2014-03-01        [2361]
1   12247 2014-03-01         [364]
2   13415 2014-03-01        [8005]
3   15976 2014-03-01       [23327]
4   16262 2014-03-01       [15097]
..    ...        ...           ...
68  70770 2014-03-01       [45684]
69  70797 2014-03-01  [3484, 7466]
70  70798 2014-03-01       [65638]
71  70890 2014-03-01       [66727]
72  71025 2014-03-01       [13043]

[73 rows x 3 columns]
Foreign Key Columns to Primary Key Tables: {'fk': 'posts', 'label': 'posts'}
Primary Key Column: None
Time Column: timestamp
-------------------------------------------

In [57]:
task.get_table("test")

------------------ Table ------------------
DataFrame:
       fk  timestamp    label
0    2007 2014-06-01  [18985]
1    2046 2014-06-01  [58397]
2    2200 2014-06-01   [1202]
3    4221 2014-06-01  [48922]
4    5516 2014-06-01  [41978]
..    ...        ...      ...
69  80232 2014-06-01   [2105]
70  80644 2014-06-01  [17017]
71  80812 2014-06-01  [27824]
72  80845 2014-06-01  [74213]
73  80896 2014-06-01  [30965]

[74 rows x 3 columns]
Foreign Key Columns to Primary Key Tables: {'fk': 'posts', 'label': 'posts'}
Primary Key Column: None
Time Column: timestamp
-------------------------------------------

In [58]:
task.get_table("test", hide_labels=True)

------------------ Table ------------------
DataFrame:
       fk  timestamp
0    2007 2014-06-01
1    2046 2014-06-01
2    2200 2014-06-01
3    4221 2014-06-01
4    5516 2014-06-01
..    ...        ...
69  80232 2014-06-01
70  80644 2014-06-01
71  80812 2014-06-01
72  80845 2014-06-01
73  80896 2014-06-01

[74 rows x 2 columns]
Foreign Key Columns to Primary Key Tables: {'fk': 'posts', 'label': 'posts'}
Primary Key Column: None
Time Column: timestamp
-------------------------------------------

## CTU-Grants

In [59]:
dataset = get_dataset("ctu-grants", download=False)
db = dataset.get_db(upto_test_timestamp=False)
db = Database(table_dict=db.table_dict)

print(f"Min timestamp: {db.min_timestamp}")
print(f"Max timestamp: {db.max_timestamp}")

Loading Database object from /home/kolesiko/.cache/relbench/ctu-grants/db...
Done in 1.68 seconds.
Min timestamp: 1900-01-01 00:00:00
Max timestamp: 2018-01-15 00:00:00

In [60]:
db.table_dict["institution"]

Table(df=
       __PK__                                    name       city_name  \
0           0                                 18F GSA      Washington
1           1                 21ST CENTURY EXPO GROUP        LANDOVER
2           2                21st Century School Fund  Washington, DC
3           3  27 International Geographical Congress      Washington
4           4                             2Cimple Inc           Plano
...       ...                                     ...             ...
16686   16686                         Zynnovation LLC      Midlothian
16687   16687                          Zyrobotics LLC         Atlanta
16688   16688                             Zysk Adam M        Palatine
16689   16689                              Zytron Ltd      Saint Paul
16690   16690                      Zzyzx Polymers LLC       Allentown

         zipcode     contact                           address   country_name  \
0      204050001           0               1800 F Street, N.W.  United States
1      207851519  2147483647                   3321-P 75TH AVE  United States
2      200094422  2027453745              1816 12th Street, NW  United States
3      200364701  2028286688              1145 17th Street N.W  United States
4      750255736  2147483647                   3101 Hoffman Dr  United States
...          ...         ...                               ...            ...
16686  231132306  2147483647         11725 N. Briarpatch Drive  United States
16687  303192002  2147483647  3522 Ashford Dunwoody Suite #105  United States
16688  600676019           0                                    United States
16689  551045701  2147483647                       85 N Cretin  United States
16690  181033160  2147483647       905 Harrison Street Ste 131  United States

                 state_name state_code
0      District of Columbia         DC
1                  Maryland         MD
2      District of Columbia         DC
3      District of Columbia         DC
4                     Texas         TX
...                     ...        ...
16686              Virginia         VA
16687               Georgia         GA
16688              Illinois         IL
16689             Minnesota         MN
16690          Pennsylvania         PA

[16691 rows x 9 columns],
  fkey_col_to_pkey_table={},
  pkey_col=__PK__,
  time_col=None)

In [61]:
db.table_dict["institution_awards"]

Table(df=
        __PK__  award_id                                               name  \
0            0         0  Virginia Polytechnic Institute and State Unive...
1            1         9                              University of Florida
2            2        26                    North Carolina State University
3            3        27                      University of Texas at Austin
4            4        31                      University of Texas at Austin
...        ...       ...                                                ...
416734  416734   9996450                           University of Washington
416735  416735   9996451                      Trustees of Boston University
416736  416736   9996452           National Bureau of Economic Research Inc
416737  416737   9996453                          Portland State University
416738  416738   9996454                           Arizona State University

          zipcode  FK_awards_award_id  FK_institution_name_zipcode
0       240610001               95446                        15668
1       326112002              228014                        15201
2       276957514              228034                        10502
3       787121532              226425                        15356
4       787121532              231553                        15356
...           ...                 ...                          ...
416734  981950001              221525                        15386
416735  022151300              221524                        14969
416736  021385398              217946                        10030
416737  972070751              218993                        11641
416738  852816011              223048                          957

[416739 rows x 6 columns],
  fkey_col_to_pkey_table={'FK_awards_award_id': 'awards', 'FK_institution_name_zipcode': 'institution'},
  pkey_col=__PK__,
  time_col=None)

In [62]:
db.table_dict["awards"]

Table(df=
        __PK__                                        award_title  \
0            0   Life and Technology in the Titelberg Settlements
1            1  Remanent Magnetism of Varved Sediments, Glacia...
2            2  Geochronology and Geology of Precambrian Rocks...
3            3  The Comparative Petrology and Geochronology of...
4            4  Sedmmentology and Geochemistry of Piston Cores...
...        ...                                                ...
430334  430334  COLLABORATIVE RESEARCH: Patterns, Dynamics, an...
430335  430335  Conference: Archival Innovations for Preservin...
430336  430336  Collaborative Research: Identifying Controls o...
430337  430337  COLLABORATIVE RESEARCH: Patterns, Dynamics, an...
430338  430338  IRES: Geoscience REsearch At the Cordillera Ta...

       award_effective_date award_expiration_date  award_amount  \
0                1900-01-01            09/30/1901         21000
1                1900-01-01            01/01/1900         25000
2                1900-01-01            01/01/1900          7500
3                1900-01-01            01/01/1900         35400
4                1900-01-01            01/01/1900          5000
...                     ...                   ...           ...
430334           2018-01-01            12/31/2020        737388
430335           2018-01-01            12/31/2018         26637
430336           2018-01-01            12/31/2020        130288
430337           2018-01-01            12/31/2020        332586
430338           2018-01-15            12/31/2020        248412

       award_instrument  organisation_code       program_officer  \
0        Standard Grant            4040400    name not available
1        Standard Grant            6030004    name not available
2        Standard Grant            6030002    name not available
3        Standard Grant            6030003    name not available
4        Standard Grant            6030003    name not available
...                 ...                ...                   ...
430334   Standard Grant            6090100      Neil R. Swanberg
430335   Standard Grant            4050000     Frederick M Kronz
430336   Standard Grant            6040300           Simone Metz
430337   Standard Grant            6090100      Neil R. Swanberg
430338   Standard Grant            1090000  Charles H. Estabrook

                                       abstract_narration min_amd_letter_date  \
0                                                                  07/25/1973
1                                                                  04/29/1974
2                                                                  04/29/1974
3                                                                  05/01/1974
4                                                                  05/03/1974
...                                                   ...                 ...
430334  The warming Arctic is reshaping the tundra lan...          04/11/2017
430335  This award supports a three-day conference tha...          06/06/2017
430336  Venting of high temperature (up to 400°C) hydr...          03/13/2017
430337  The warming Arctic is reshaping the tundra lan...          04/11/2017
430338  Non-technical abstract<br/><br/>The Geoscience...          04/13/2017

       max_amd_letter_date  arra_amount  FK_organization_organisation_code
0               07/25/1973            0                                203
1               06/16/1975            0                                289
2               04/29/1974            0                                287
3               05/01/1974            0                                288
4               05/03/1974            0                                288
...                    ...          ...                                ...
430334          04/11/2017            0                                330
430335          06/06/2017            0                                208
430336          03/13/2017            0                                321
430337          04/11/2017            0                                330
430338          04/13/2017            0                                 53

[430339 rows x 13 columns],
  fkey_col_to_pkey_table={'FK_organization_organisation_code': 'organization'},
  pkey_col=__PK__,
  time_col=award_effective_date)

In [63]:
db.table_dict["organization"]

Table(df=
     __PK__                                  division  \
0         0
1         1
2         2
3         3
4         4
..      ...                                       ...
470     470  Direct For Education and Human Resources
471     471              National Coordination Office
472     472   Natl Nanotechnology Coordinating Office
473     473                  Office Of Polar Programs
474     474

                                 directorate
0
1                     National Science Board
2                Office Of Inspector General
3                Office Of Inspector General
4                Office Of Inspector General
..                                       ...
470         Division Of Research On Learning
471             National Coordination Office
472  Natl Nanotechnology Coordinating Office
473                 Arctic Sciences Division
474

[475 rows x 3 columns],
  fkey_col_to_pkey_table={},
  pkey_col=__PK__,
  time_col=None)

### Awards Institution Static Task

In [64]:
from rtgl_tasks.tasks import GrantsAwardsInstitutionStatTask

In [65]:
task = GrantsAwardsInstitutionStatTask()

In [66]:
task.get_table("train")

------------------ Table ------------------
DataFrame:
            fk  label
153174  158242  10798
323592  333910   7321
177988  183948   1393
227694  235514   2375
202910  209940  15258
...        ...    ...
229372  237222  15342
88249    90903   6693
55694    57494   9302
291611  301100  15343
147039  151805   8867

[333369 rows x 2 columns]
Foreign Key Columns to Primary Key Tables: {'fk': 'awards'}
Primary Key Column: None
Time Column: None
-------------------------------------------

In [67]:
task.get_table("val")

------------------ Table ------------------
DataFrame:
            fk  label
172180  177930  10620
30080    31087   6682
267873  276739   5081
411556  424995  15386
256297  264829  15293
...        ...    ...
220606  228243  14133
160665  166010  15279
220928  228578  15169
300106  309818   7321
405932  419185  15217

[41671 rows x 2 columns]
Foreign Key Columns to Primary Key Tables: {'fk': 'awards'}
Primary Key Column: None
Time Column: None
-------------------------------------------

In [68]:
task.get_table("test")

------------------ Table ------------------
DataFrame:
            fk  label
19          19  14892
36          36   3307
43          44   7321
45          46   3512
51          52  15282
...        ...    ...
416682  430309  15174
416688  430316  15169
416700  430328  15211
416703  430331  15231
416705  430333  16367

[41671 rows x 2 columns]
Foreign Key Columns to Primary Key Tables: {'fk': 'awards'}
Primary Key Column: None
Time Column: None
-------------------------------------------

In [69]:
task.get_table("test", hide_labels=True)

------------------ Table ------------------
DataFrame:
            fk
19          19
36          36
43          44
45          46
51          52
...        ...
416682  430309
416688  430316
416700  430328
416703  430331
416705  430333

[41671 rows x 1 columns]
Foreign Key Columns to Primary Key Tables: {'fk': 'awards'}
Primary Key Column: None
Time Column: None
-------------------------------------------

### Count Institution Awards Static Task

In [70]:
from rtgl_tasks.tasks import GrantsCountInstitutionAwardsStatTask

In [71]:
task = GrantsCountInstitutionAwardsStatTask()

In [72]:
task.get_table("train")

------------------ Table ------------------
DataFrame:
          fk  label
5852    5852      1
14558  14558      1
7044    7044      2
2683    2683      1
291      291     24
...      ...    ...
13582  13582      2
11048  11048      1
10053  10053      2
10851  10851      1
3384    3384     10

[13353 rows x 2 columns]
Foreign Key Columns to Primary Key Tables: {'fk': 'institution'}
Primary Key Column: None
Time Column: None
-------------------------------------------

In [73]:
task.get_table("val")

------------------ Table ------------------
DataFrame:
          fk  label
13621  13621      2
15062  15062      1
1633    1633      2
1331    1331      4
8135    8135      1
...      ...    ...
2079    2079      1
1252    1252      1
153      153      1
13042  13042      8
1382    1382      2

[1669 rows x 2 columns]
Foreign Key Columns to Primary Key Tables: {'fk': 'institution'}
Primary Key Column: None
Time Column: None
-------------------------------------------

In [74]:
task.get_table("test")

------------------ Table ------------------
DataFrame:
          fk  label
1          1      1
54        54      1
60        60      3
72        72     44
78        78      1
...      ...    ...
16641  16641      1
16645  16645      1
16656  16656      1
16662  16662      1
16688  16688      1

[1669 rows x 2 columns]
Foreign Key Columns to Primary Key Tables: {'fk': 'institution'}
Primary Key Column: None
Time Column: None
-------------------------------------------

In [75]:
task.get_table("test", hide_labels=True)

------------------ Table ------------------
DataFrame:
          fk
1          1
54        54
60        60
72        72
78        78
...      ...
16641  16641
16645  16645
16656  16656
16662  16662
16688  16688

[1669 rows x 1 columns]
Foreign Key Columns to Primary Key Tables: {'fk': 'institution'}
Primary Key Column: None
Time Column: None
-------------------------------------------

### Organization Awards Amount Static Task

In [76]:
from rtgl_tasks.tasks import GrantsOrganizationAwardsAmountStatTask

In [77]:
task = GrantsOrganizationAwardsAmountStatTask()

In [78]:
task.get_table("train")

------------------ Table ------------------
DataFrame:
      fk         label
375  375  3.486535e+06
422  422  1.408279e+08
9      9  7.496286e+06
73    73  2.297054e+07
354  354  2.286982e+06
..   ...           ...
216  216  3.253000e+05
279  279  2.794530e+07
451  451  2.216656e+08
409  409  7.555105e+07
337  337  4.400150e+09

[380 rows x 2 columns]
Foreign Key Columns to Primary Key Tables: {'fk': 'organization'}
Primary Key Column: None
Time Column: None
-------------------------------------------

In [79]:
task.get_table("val")

------------------ Table ------------------
DataFrame:
      fk         label
160  160  8.355181e+07
71    71  6.597130e+05
43    43  5.037110e+05
166  166  1.291210e+05
106  106  1.757850e+06
102  102  1.699146e+08
434  434  1.517996e+06
80    80  1.075014e+09
151  151  7.540894e+08
464  464  9.542099e+07
264  264  1.558392e+06
315  315  9.308595e+08
270  270  1.624519e+07
236  236  1.400996e+07
309  309  4.559082e+08
344  344  5.903201e+06
456  456  1.075477e+06
214  214  7.264700e+04
273  273  2.064336e+08
50    50  9.365948e+07
34    34  1.800000e+04
359  359  7.948800e+04
330  330  1.680658e+09
241  241  5.447420e+05
134  134  5.324142e+08
269  269  4.816176e+07
328  328  3.340100e+06
53    53  1.304259e+09
443  443  7.707410e+07
91    91  9.244109e+07
105  105  1.824817e+07
190  190  3.920640e+05
345  345  2.806089e+09
48    48  2.757151e+06
385  385  1.400000e+04
201  201  1.051661e+09
473  473  7.312400e+04
212  212  6.063520e+05
252  252  1.068063e+06
49    49  7.652000e+04
149  149  2.251039e+08
88    88  8.000000e+04
413  413  1.877272e+07
313  313  7.870061e+07
348  348  5.542680e+05
169  169  1.000000e+00
276  276  7.028622e+08
58    58  3.201000e+04
Foreign Key Columns to Primary Key Tables: {'fk': 'organization'}
Primary Key Column: None
Time Column: None
-------------------------------------------

In [80]:
task.get_table("test")

------------------ Table ------------------
DataFrame:
      fk         label
1      1  1.175464e+06
13    13  7.202595e+07
20    20  9.300000e+03
21    21  1.993315e+06
52    52  1.000000e+00
54    54 -7.965000e+03
87    87  8.146421e+06
99    99  9.864537e+08
121  121  6.168333e+08
130  130  7.619019e+07
161  161  9.106748e+07
174  174  9.000000e+00
187  187  1.305562e+07
188  188  5.745053e+06
189  189  1.159869e+07
191  191  2.366599e+06
205  205  5.118538e+07
207  207  2.875849e+06
217  217  4.274579e+07
235  235  4.000000e+04
243  243  2.322981e+07
251  251  5.999737e+07
257  257  1.065536e+08
259  259  3.676530e+05
263  263  1.408000e+04
293  293  4.257634e+06
295  295  2.167924e+07
303  303  1.007230e+08
306  306  6.781902e+07
308  308  2.674109e+07
319  319  1.918133e+09
339  339  7.648750e+05
343  343  3.264060e+05
350  350  3.332669e+09
363  363  1.084508e+08
366  366  1.253801e+09
372  372  0.000000e+00
387  387  2.728790e+08
389  389  1.445735e+09
420  420  1.388119e+09
435  435  7.904832e+06
449  449  8.404440e+06
458  458  8.240110e+07
462  462  9.127190e+06
467  467  1.093722e+08
471  471  3.954937e+07
474  474  3.120000e+04
Foreign Key Columns to Primary Key Tables: {'fk': 'organization'}
Primary Key Column: None
Time Column: None
-------------------------------------------

In [81]:
task.get_table("test", hide_labels=True)

------------------ Table ------------------
DataFrame:
      fk
1      1
13    13
20    20
21    21
52    52
54    54
87    87
99    99
121  121
130  130
161  161
174  174
187  187
188  188
189  189
191  191
205  205
207  207
217  217
235  235
243  243
251  251
257  257
259  259
263  263
293  293
295  295
303  303
306  306
308  308
319  319
339  339
343  343
350  350
363  363
366  366
372  372
387  387
389  389
420  420
435  435
449  449
458  458
462  462
467  467
471  471
474  474
Foreign Key Columns to Primary Key Tables: {'fk': 'organization'}
Primary Key Column: None
Time Column: None
-------------------------------------------

## CTU-Seznam

In [82]:
dataset = get_dataset("ctu-seznam", download=False)
db = dataset.get_db(upto_test_timestamp=False)
db = Database(table_dict=db.table_dict)

print(f"Min timestamp: {db.min_timestamp}")
print(f"Max timestamp: {db.max_timestamp}")

Loading Database object from /home/kolesiko/.cache/relbench/ctu-seznam/db...
Done in 0.12 seconds.
Min timestamp: 2012-08-01 00:00:00
Max timestamp: 2015-10-01 00:00:00

In [83]:
db

================= Database ================
Table Name: probehnuto_mimo_penezenku
Table(df=
        __PK__  client_id Month_Year probehla_inzerce_mimo_penezenku  \
0            0       3901 2012-08-01                             ANO
1            1      99523 2012-08-01                             ANO
2            2      99521 2012-08-01                             ANO
3            3      99517 2012-08-01                             ANO
4            4      14536 2012-08-01                             ANO
...        ...        ...        ...                             ...
599381  599381     937998 2015-10-01                             ANO
599382  599382     937324 2015-10-01                             ANO
599383  599383      10853 2015-10-01                             ANO
599384  599384      10713 2015-10-01                             ANO
599385  599385    9805032 2015-10-01                             ANO

        FK_client_client_id
0                         0
1                     27001
2                     26999
3                     26998
4                      3170
...                     ...
599381                35891
599382                35868
599383                 2154
599384                 2117
599385                73385

[599386 rows x 5 columns],
  fkey_col_to_pkey_table={'FK_client_client_id': 'client'},
  pkey_col=__PK__,
  time_col=Month_Year)
Table Name: dobito
Table(df=
        __PK__  client_id month_year_datum_transakce sluzba  kc_dobito  \
0            0    8674551                 2012-08-01      g     6280.0
1            1      95534                 2012-08-01      g     9420.0
2            2    1034121                 2012-08-01      g    37680.0
3            3      97633                 2012-08-01      g    30144.0
4            4    1754378                 2012-08-01      g    37680.0
...        ...        ...                        ...    ...        ...
554341  554341      95913                 2015-10-01      h    5187.28
554342  554342    9771099                 2015-10-01      d    18164.9
554343  554343     957969                 2015-10-01      h    1296.82
554344  554344     860538                 2015-10-01      d    53380.0
554345  554345      81055                 2015-10-01      a     6280.0

        FK_client_client_id
0                     55142
1                     25542
2                     39257
3                     26304
4                     47495
...                     ...
554341                25680
554342                68633
554343                36637
554344                33208
554345                20551

[554346 rows x 6 columns],
  fkey_col_to_pkey_table={'FK_client_client_id': 'client'},
  pkey_col=__PK__,
  time_col=month_year_datum_transakce)
Table Name: probehnuto
Table(df=
          __PK__  client_id month_year_datum_transakce sluzba  kc_proklikano  \
0              0    1201279                 2012-08-01      d         797.56
1              1    8648797                 2012-08-01      d        15700.0
2              2      35871                 2012-08-01      d         474.14
3              3     921298                 2012-08-01      d         1821.2
4              4      63408                 2012-08-01      d        10205.0
...          ...        ...                        ...    ...            ...
1462073  1462073      94406                 2015-10-01      a          973.4
1462074  1462074      89442                 2015-10-01      a        2141.48
1462075  1462075      55724                 2015-10-01      a        10032.3
1462076  1462076      49210                 2015-10-01      a       31739.12
1462077  1462077     946957                 2015-10-01   <NA>         153.86

         FK_client_client_id
0                      44384
1                      51736
2                       8142
3                      35302
4                      14895
...                      ...
1462073                25137
1462074                23358
1462075                12668
1462076                11061
1462077                36237

[1462078 rows x 6 columns],
  fkey_col_to_pkey_table={'FK_client_client_id': 'client'},
  pkey_col=__PK__,
  time_col=month_year_datum_transakce)
Table Name: client
Table(df=
       __PK__               kraj     obor
0           0           Vysočina    Vilma
1           1  Jihomoravský kraj    Leona
2           2       Zlínský kraj   Vladan
3           3       Ústecký kraj    Sonja
4           4       Ústecký kraj  Bohdana
...       ...                ...      ...
73442   73442     Jihočeský kraj     <NA>
73443   73443               <NA>     <NA>
73444   73444               <NA>     <NA>
73445   73445  Jihomoravský kraj    Leona
73446   73446               <NA>     <NA>

[73447 rows x 3 columns],
  fkey_col_to_pkey_table={},
  pkey_col=__PK__,
  time_col=None)

### Client Out of Wallet Temporal Task

In [84]:
from rtgl_tasks.tasks import SeznamClientOutOfWalletTmpTask

In [85]:
task = SeznamClientOutOfWalletTmpTask()

In [90]:
task.get_table("train")

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

------------------ Table ------------------
DataFrame:
           fk  timestamp  label
0           4 2012-08-13   True
1           8 2012-08-13   True
2           9 2012-08-13   True
3          11 2012-08-13   True
4          13 2012-08-13   True
...       ...        ...    ...
787290  73396 2015-01-30  False
787291  73424 2015-01-30  False
787292  73429 2015-01-30  False
787293  73434 2015-01-30  False
787294  73442 2015-01-30  False

[787295 rows x 3 columns]
Foreign Key Columns to Primary Key Tables: {'fk': 'client'}
Primary Key Column: None
Time Column: timestamp
-------------------------------------------

In [91]:
task.get_table("val")

------------------ Table ------------------
DataFrame:
           fk  timestamp  label
0           0 2015-03-01  False
1           1 2015-03-01  False
2           2 2015-03-01  False
3           3 2015-03-01  False
4           4 2015-03-01  False
...       ...        ...    ...
135097  73429 2015-04-30  False
135098  73434 2015-04-30  False
135099  73436 2015-04-30  False
135100  73441 2015-04-30  False
135101  73442 2015-04-30  False

[135102 rows x 3 columns]
Foreign Key Columns to Primary Key Tables: {'fk': 'client'}
Primary Key Column: None
Time Column: timestamp
-------------------------------------------

In [92]:
task.get_table("test")

------------------ Table ------------------
DataFrame:
           fk  timestamp  label
0           0 2015-07-01  False
1           1 2015-07-01  False
2           2 2015-07-01  False
3           3 2015-07-01  False
4           4 2015-07-01  False
...       ...        ...    ...
145534  73425 2015-08-30  False
145535  73429 2015-08-30  False
145536  73436 2015-08-30  False
145537  73441 2015-08-30  False
145538  73442 2015-08-30  False

[145539 rows x 3 columns]
Foreign Key Columns to Primary Key Tables: {'fk': 'client'}
Primary Key Column: None
Time Column: timestamp
-------------------------------------------

### Client Servis Temporal Task

In [93]:
from rtgl_tasks.tasks import SeznamClientServisTmpTask

In [94]:
task = SeznamClientServisTmpTask()

In [95]:
task.get_table("train")

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

------------------ Table ------------------
DataFrame:
           fk  timestamp   label
0           0 2012-08-13     [d]
1           1 2012-08-13     [d]
2           2 2012-08-13     [d]
3           6 2012-08-13     [d]
4          17 2012-08-13     [e]
...       ...        ...     ...
832906  73437 2015-01-30     [h]
832907  73438 2015-01-30  [d, a]
832908  73439 2015-01-30     [e]
832909  73443 2015-01-30  [d, h]
832910  73444 2015-01-30  [h, d]

[832911 rows x 3 columns]
Foreign Key Columns to Primary Key Tables: {'fk': 'client'}
Primary Key Column: None
Time Column: timestamp
-------------------------------------------

In [96]:
task.get_table("val")

------------------ Table ------------------
DataFrame:
          fk  timestamp      label
0          1 2015-03-31  [a, d, h]
1          2 2015-03-31     [d, a]
2          4 2015-03-31     [a, b]
3          5 2015-03-31     [h, d]
4          7 2015-03-31        [d]
...      ...        ...        ...
72057  73438 2015-04-30     [a, d]
72058  73439 2015-04-30        [e]
72059  73443 2015-04-30     [h, d]
72060  73444 2015-04-30        [h]
72061  73445 2015-04-30        [h]

[72062 rows x 3 columns]
Foreign Key Columns to Primary Key Tables: {'fk': 'client'}
Primary Key Column: None
Time Column: timestamp
-------------------------------------------

In [97]:
task.get_table("test")

------------------ Table ------------------
DataFrame:
          fk  timestamp      label
0          1 2015-07-31  [a, d, h]
1          2 2015-07-31        [a]
2          4 2015-07-31     [a, b]
3          5 2015-07-31        [h]
4          7 2015-07-31        [d]
...      ...        ...        ...
69522  73439 2015-08-30        [e]
69523  73443 2015-08-30     [d, h]
69524  73444 2015-08-30        [h]
69525  73445 2015-08-30     [h, d]
69526  73446 2015-08-30        [d]

[69527 rows x 3 columns]
Foreign Key Columns to Primary Key Tables: {'fk': 'client'}
Primary Key Column: None
Time Column: timestamp
-------------------------------------------

### Client First Servis Temporal Task

In [98]:
from rtgl_tasks.tasks import SeznamClientFirstServisTmpTask

In [99]:
task = SeznamClientFirstServisTmpTask()

In [100]:
task.get_table("train")

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

------------------ Table ------------------
DataFrame:
           fk  timestamp label
0           0 2012-08-13     d
1           1 2012-08-13     d
2           2 2012-08-13     d
3           6 2012-08-13     d
4          17 2012-08-13     e
...       ...        ...   ...
831221  73437 2015-01-30     h
831222  73438 2015-01-30     d
831223  73439 2015-01-30     e
831224  73443 2015-01-30     h
831225  73444 2015-01-30     d

[831226 rows x 3 columns]
Foreign Key Columns to Primary Key Tables: {'fk': 'client'}
Primary Key Column: None
Time Column: timestamp
-------------------------------------------

In [101]:
task.get_table("val")

------------------ Table ------------------
DataFrame:
          fk  timestamp label
0          1 2015-03-31     h
1          2 2015-03-31     d
2          4 2015-03-31     a
3          5 2015-03-31     h
4          7 2015-03-31     d
...      ...        ...   ...
71964  73438 2015-04-30     d
71965  73439 2015-04-30     e
71966  73443 2015-04-30     h
71967  73444 2015-04-30     h
71968  73445 2015-04-30     h

[71969 rows x 3 columns]
Foreign Key Columns to Primary Key Tables: {'fk': 'client'}
Primary Key Column: None
Time Column: timestamp
-------------------------------------------

In [102]:
task.get_table("test")

------------------ Table ------------------
DataFrame:
          fk  timestamp label
0          1 2015-07-31     d
1          2 2015-07-31     a
2          4 2015-07-31     a
3          5 2015-07-31     h
4          7 2015-07-31     d
...      ...        ...   ...
69280  73439 2015-08-30     e
69281  73443 2015-08-30     d
69282  73444 2015-08-30     h
69283  73445 2015-08-30     h
69284  73446 2015-08-30     d

[69285 rows x 3 columns]
Foreign Key Columns to Primary Key Tables: {'fk': 'client'}
Primary Key Column: None
Time Column: timestamp
-------------------------------------------

In [103]:
task.get_table("test", hide_labels=True)

------------------ Table ------------------
DataFrame:
          fk  timestamp
0          1 2015-07-31
1          2 2015-07-31
2          4 2015-07-31
3          5 2015-07-31
4          7 2015-07-31
...      ...        ...
69280  73439 2015-08-30
69281  73443 2015-08-30
69282  73444 2015-08-30
69283  73445 2015-08-30
69284  73446 2015-08-30

[69285 rows x 2 columns]
Foreign Key Columns to Primary Key Tables: {'fk': 'client'}
Primary Key Column: None
Time Column: timestamp
-------------------------------------------

### Client Spending Temporal Task

In [104]:
from rtgl_tasks.tasks import SeznamClientSpendingTmpTask

In [105]:
task = SeznamClientSpendingTmpTask()

In [106]:
task.get_table("train")

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

------------------ Table ------------------
DataFrame:
           fk  timestamp     label
0           0 2012-08-13   5294.04
1           1 2012-08-13   5162.16
2           2 2012-08-13   2351.86
3           6 2012-08-13  22987.94
4          17 2012-08-13   5652.00
...       ...        ...       ...
843957  73437 2015-01-30     18.84
843958  73438 2015-01-30  32517.84
843959  73439 2015-01-30  25744.86
843960  73443 2015-01-30   3290.72
843961  73444 2015-01-30   2882.52

[843962 rows x 3 columns]
Foreign Key Columns to Primary Key Tables: {'fk': 'client'}
Primary Key Column: None
Time Column: timestamp
-------------------------------------------

In [107]:
task.get_table("val")

------------------ Table ------------------
DataFrame:
          fk  timestamp     label
0          1 2015-03-31   9837.62
1          2 2015-03-31   2584.22
2          4 2015-03-31  11677.66
3          5 2015-03-31  13495.72
4          7 2015-03-31  42317.78
...      ...        ...       ...
72761  73438 2015-04-30   3906.16
72762  73439 2015-04-30  14440.86
72763  73443 2015-04-30   2053.56
72764  73444 2015-04-30     47.10
72765  73445 2015-04-30    624.86

[72766 rows x 3 columns]
Foreign Key Columns to Primary Key Tables: {'fk': 'client'}
Primary Key Column: None
Time Column: timestamp
-------------------------------------------

In [108]:
task.get_table("test")

------------------ Table ------------------
DataFrame:
          fk  timestamp     label
0          1 2015-07-31   8512.54
1          2 2015-07-31   1946.80
2          4 2015-07-31  12246.00
3          5 2015-07-31    618.58
4          7 2015-07-31  32357.70
...      ...        ...       ...
70181  73439 2015-08-30  12924.24
70182  73443 2015-08-30   9473.38
70183  73444 2015-08-30     40.82
70184  73445 2015-08-30   4502.76
70185  73446 2015-08-30    753.60

[70186 rows x 3 columns]
Foreign Key Columns to Primary Key Tables: {'fk': 'client'}
Primary Key Column: None
Time Column: timestamp
-------------------------------------------

In [109]:
task.get_table("test", hide_labels=True)

------------------ Table ------------------
DataFrame:
          fk  timestamp
0          1 2015-07-31
1          2 2015-07-31
2          4 2015-07-31
3          5 2015-07-31
4          7 2015-07-31
...      ...        ...
70181  73439 2015-08-30
70182  73443 2015-08-30
70183  73444 2015-08-30
70184  73445 2015-08-30
70185  73446 2015-08-30

[70186 rows x 2 columns]
Foreign Key Columns to Primary Key Tables: {'fk': 'client'}
Primary Key Column: None
Time Column: timestamp
-------------------------------------------